name: Actor Core Release

on:
  push:
    tags:
      - 'actor-core-v*'

env:
  CARGO_TERM_COLOR: always
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  working-directory: ./actor-core


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  crates:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cargo login
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
        run: cargo login ${{ env.CRATES_TOKEN }}
      - name: Cargo publish
        run: cargo publish --no-verify
        working-directory: ${{ env.working-directory }}/rust

  npm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: NPM Publish
        run: npm publish --access public
        working-directory: ${{ env.working-directory }}/assemblyscript
